### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'beta'

### ISSUE THREAD

**Issue by JerrryNie** [seanie12/SWEP#2]
Hi! In your code, it seems that the setting of 'beta' hyperparameter is lost. Can you fix it in a new commit ?

**Comment by seanie12** [comment]
Thank you for pointing out my mistake.

We set the beta as 1.0 for BERT and Electra  model.

I will fix it .

**Comment by JerrryNie** [comment]
> Thank you for pointing out my mistake.
> 
> We set the beta as 1.0 for BERT and Electra model.
> 
> I will fix it .

Thanks a lot!
